Update nodejs.yaml

diff --git a/github-workflows/nodejs.yaml b/github-workflows/nodejs.yaml
--- a/github-workflows/nodejs.yaml
+++ b/github-workflows/nodejs.yaml
@@ -42,7 +42,7 @@ jobs:
           if [ -z "${{ vars.SERVER_DEPLOY_PATH }}" ]; then echo "❌ Missing var: SERVER_DEPLOY_PATH"; exit 1; fi
           if [ -z "${{ secrets.SERVER_HOST }}" ]; then echo "❌ Missing secret: SERVER_HOST"; exit 1; fi
           if [ -z "${{ secrets.SERVER_USER }}" ]; then echo "❌ Missing secret: SERVER_USER"; exit 1; fi
-          if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then echo "❌ Missing secret: SERVER_SSH_KEY"; exit 1; fi
+          if [ -z "${{ secrets.SERVER_PASSWORD }}" ]; then echo "❌ Missing secret: SERVER_PASSWORD"; exit 1; fi
           if [ -z "${{ secrets.APP_ENVS }}" ]; then echo "❌ Missing secret: APP_ENVS (.env for server)"; exit 1; fi
 
           if [ ! -f "ecosystem.config.js" ]; then echo "❌ Missing file: ecosystem.config.js"; exit 1; fi
@@ -52,7 +52,7 @@ jobs:
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
+          password: ${{ secrets.SERVER_PASSWORD }}
           script: |
             if [ ! -f "${{ vars.SERVER_DEPLOY_PATH }}/.env" ]; then
                 echo "${{ secrets.APP_ENVS }}" > "${{ vars.SERVER_DEPLOY_PATH }}/.env"
@@ -88,7 +88,7 @@ jobs:
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
+          password: ${{ secrets.SERVER_PASSWORD }}
           port: 22
           source: ". , !node_modules"
           target: ${{ vars.SERVER_DEPLOY_PATH }}
@@ -98,7 +98,7 @@ jobs:
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
+          password: ${{ secrets.SERVER_PASSWORD }}
           port: 22
           script: |
             cd ${{ vars.SERVER_DEPLOY_PATH }}
